services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zettelearn-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@postgresql-database-w8prxmb4woa34dl02tnxhbd0:5432/postgres
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - zettelearn

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: zettelearn-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - zettelearn

networks:
  zettelearn:
    driver: bridge
